name: Build and Test

on:
  push:

jobs:
  quality:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build web app
        run: pnpm --filter @katebrune/web build

      - name: Unit tests
        run: pnpm --filter @katebrune/web test
